name: 🐞 Bug Report
description: Create a report to help us improve.
title: "[Bug]: "
labels: [ "bug" ]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: checkboxes
    attributes:
      label: Is there an existing issue for this?
      description: Please search to see if an issue already exists for the bug you encountered.
      options:
        - label: I have searched the existing issues
          required: true
  - type: checkboxes
    attributes:
      label: Self-training on how to write a bug report
      description: High quality bug report can help the team save time and improve the chance of getting fixed. Please read [how to write a bug report](https://www.browserstack.com/guide/how-to-write-a-bug-report) before submitting your issue.
      options:
        - label: I have learned [how to write a bug report](https://www.browserstack.com/guide/how-to-write-a-bug-report)
          required: true
  - type: checkboxes
    attributes:
      label: Code of conduct
      description: I have read and agree to adhere to the [Code of Conduct](CODE_OF_CONDUCT.md).
      options:
        - label: I have read and agree to adhere to the [Code of Conduct](CODE_OF_CONDUCT.md)
          required: true
  - type: dropdown
    id: project
    attributes:
      label: Project
      description: What project does this relate to?
      options:
        - Staking Portal
        - Other
      default: 0
    validations:
      required: true
  - type: dropdown
    id: device
    attributes:
      label: Device Type
      description: What device type are you seeing this issue on?
      options:
        - Desktop
        - Mobile
        - N/A
      default: 0
    validations:
      required: true
  - type: input
    attributes:
      label: Browser
      description: What browser are you seeing this issue on?
      placeholder: eg. Chrome 126
    validations:
      required: true
  - type: input
    attributes:
      label: Browser Resolution
      description: What browser resolution does this issue occur on? You can find this easily using tools like https://mdigi.tools/browser-resolution/
      placeholder: eg. Fedora Linux 39
    validations:
      required: true
  - type: input
    attributes:
      label: Operating System
      description: What operating system are you seeing this issue on?
      placeholder: eg. Fedora Linux 39
    validations:
      required: true
  - type: input
    attributes:
      label: What wallet are you using and how are you connecting your wallet? (if applicable)
      description: If your issue relates to any wallet functionality, please provide the wallet name and how you are connecting your wallet.
      placeholder: eg. Metamask Browser Extension
    validations:
      required: false
  - type: textarea
    attributes:
      label: Current Behavior
      description: A concise description of what you're experiencing. Please include screenshots and recordings if applicable.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Expected Behavior
      description: A concise description of what you expected to happen.
    validations:
      required: false
  - type: textarea
    attributes:
      label: Steps To Reproduce
      description: Steps to reproduce the behavior.
      placeholder: |
        1. In this environment...
        1. With this config...
        1. Run '...'
        1. See error...
    validations:
      required: false
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
  - type: textarea
    attributes:
      label: Anything else?
      description: |
        Links? References? Anything that will give us more context about the issue you are encountering!
        
        Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
    validations:
      required: false
