name: 🚀 Feature request
description: Suggest an idea for a new feature
title: '[Feature]: '
labels: [ "enhancement" ]
body:
  - type: checkboxes
    attributes:
      label: Is there an existing request for feature?
      description: Please search to see if an issue already exists for the feature you are requesting.
      options:
        - label: I have searched the existing issues
          required: true
  - type: dropdown
    id: project
    attributes:
      label: Project
      description: What project does this relate to?
      options:
        - Staking Portal
        - Other
      default: 0
    validations:
      required: true
  - type: dropdown
    id: type
    attributes:
      label: Feature Request Type
      description: What kind of feature request is this?
      options:
        - Solve a problem
        - Add a new feature
        - Improve an existing feature
        - Other
      default: 0
    validations:
      required: true
  - type: textarea
    attributes:
      label: Feature Motivation
      description: |
        A clear and concise description of the feature motivation. 
        Eg. I'm always frustrated when [...] so I would like to see [...]
        If you are suggesting a new feature, please explain why you think it should be added.
    validations:
      required: false
  - type: textarea
    attributes:
      label: Request Details
      description: |
        A clear and concise description of the feature and any details that would be helpful to implement it.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Anything else?
      description: |
        Add any other context or screenshots about the feature request here
    validations:
      required: false
